version: "3.9"

services:
    db:
        image: postgis/postgis:17-3.4
        container_name: postgis17
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: geo
        ports:
            - "15432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./data:/csv_data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U edge"]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    postgres_data:
